### PR TITLE
Adaptation for mobile screens

### PR DESCRIPTION
**Pull request by avele**

### CODE REVIEW

**Comment by neongreen** [comment]
- [x] Weird font size:

**Comment by neongreen** [comment]
- [x] Misaligned icons, specifically the cog. A slightly bigger right margin for icons might also be good.



- [x] Same for the category menu.

**Comment by neongreen** [comment]
- [x] The footer needs some vertical padding.

**Comment by neongreen** [comment]
- [x] The search input is too close to the logo (maybe hide the logo entirely when the search is open on mobile?)

**Review by neongreen — CHANGES_REQUESTED** [review]
I left some comments.

**Comment by avele** [comment]
> * [x]  Misaligned icons, specifically the cog. A slightly bigger right margin for icons might also be good.
> 
> 
> 
> * [x]  Same for the category menu.
> 
> 

Fixed in another PR #341

**Comment by avele** [comment]
> * [x]  The search input is too close to the logo (maybe hide the logo entirely when the search is open on mobile?)
> 
> 

The search icon button hides search input and logo becomes fully visible

**Comment by neongreen** [comment]
- [x] Buttons in the conflict resolution dialog don't fit

image

**Pull request merged**
